'use strict';
const app=document.querySelector('#app');
let state, lesson, journey, attemptId, feedback, screen='learn', dataset='synthetic';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
async function api(path,data){
 const res=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});
 const body=await res.json(); if(!res.ok)throw new Error(body.error||'Request failed'); return body;
}
function error(e){const el=document.querySelector('#error');el.textContent=e.message||'Something went wrong. Please retry.';el.hidden=false;setTimeout(()=>el.hidden=true,7000);}
function bind(id,fn){const el=document.getElementById(id);if(!el)return;el.addEventListener('click',async()=>{el.disabled=true;try{await fn();}catch(e){error(e);}finally{el.disabled=false;}});}
function render(html){app.innerHTML=html;const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo(0,0);}
function tabs(which){screen=which;document.querySelector('#learn-tab').classList.toggle('active',which==='learn');document.querySelector('#insights-tab').classList.toggle('active',which==='insights');}
function progress(step){return `<div class="progress"><span class="${step===1?'on':''}">01 Learn</span><span>→</span><span class="${step===2?'on':''}">02 Practice</span><span>→</span><span class="${step===3?'on':''}">03 Reflect & return</span></div>`;}
function home(){
 tabs('learn');const plan=state.plan;
 render(`<section class="hero"><div><div class="eyebrow">A little progress, every day</div><h1>Don’t just get the answer.<br>Build the understanding.</h1><p class="muted">One short lesson. Three thoughtful questions. A clear next step, shaped around what you missed.</p></div><aside class="loop-art"><div class="eyebrow">The learning loop</div><h2>Small steps.<br>Lasting understanding.</h2><p>Make your next session easier to start.</p><div class="steps"><span>Learn</span><span>Practice</span><span>Reflect</span><span>Return ↻</span></div></aside></section>
 ${plan?`<section class="card plan"><div><div class="eyebrow">${plan.completed_at?'Revision completed':'Your next small step'}</div><h3>${esc(state.lessons.find(l=>l.id===plan.lesson_id)?.title)}</h3><p class="muted">${plan.completed_at?'You closed the loop. Start another lesson below.':`Suggested return: ${esc(fmt(plan.due_at))}. You can also practice early.`}</p></div>${!plan.completed_at?'<button id="review" class="primary">Open revision →</button>':''}</section>`:''}
 <div class="section-title"><h2>Choose your focus</h2><span class="muted small">Original mini lessons · No exam guarantees</span></div><div class="grid">${state.lessons.map(l=>`<article class="card"><div class="meta">${esc(l.subject)} · ${l.minutes} MIN · 3 QUESTIONS</div><h2>${esc(l.title)}</h2><p>${esc(l.goal)}</p><button class="primary" id="start-${esc(l.id)}">Start lesson →</button></article>`).join('')}</div>
 ${state.latest?'<div class="actions"><button id="last-feedback" class="secondary">Reopen last feedback</button></div>':''}
 <p class="note">Built to explore one hypothesis: does specific, actionable feedback help learners return? Product insights show the instrumentation and a clearly labelled synthetic example.</p>`);
 state.lessons.forEach(l=>bind('start-'+l.id,()=>start(l)));
 bind('review',()=>revision());bind('last-feedback',()=>openFeedback(state.latest));
}
async function start(l){
 lesson=l;journey=crypto.randomUUID();attemptId=crypto.randomUUID();
 await api('/api/start',{lesson_id:l.id,journey_id:journey});showLesson();
}
function showLesson(){
 render(`${progress(1)}<div class="eyebrow">${esc(lesson.subject)} · ${lesson.minutes} MINUTES</div><h1>${esc(lesson.title)}</h1><p class="muted">${esc(lesson.goal)}</p><div class="content-layout"><section>${lesson.cards.map((c,i)=>`<article class="card lesson-card"><span class="num">IDEA 0${i+1}</span><h3>${esc(c.heading)}</h3><p>${esc(c.text)}</p></article>`).join('')}<div class="actions"><button id="practice" class="primary">Ready? Try three questions →</button><button id="back" class="secondary">Back to lessons</button></div></section><aside class="card side"><div class="eyebrow">Before you practice</div><h2>Read for the distinction.</h2><p class="muted">Ask yourself how the ideas differ. You’ll receive feedback after answering all three questions.</p><p class="note">Source for context: <a href="${esc(lesson.source)}" target="_blank" rel="noopener">reference material ↗</a></p></aside></div>`);
 bind('practice',()=>quiz());bind('back',()=>home());
}
function questions(l){return l.questions.map((q,i)=>`<fieldset class="question"><legend>${i+1}. ${esc(q.prompt)}</legend>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}" required><span>${esc(o)}</span></label>`).join('')}</fieldset>`).join('');}
function answers(l){return l.questions.map((_,i)=>{const x=app.querySelector(`input[name="q${i}"]:checked`);if(!x)throw new Error('Choose an answer for every question.');return Number(x.value);});}
function quiz(){
 render(`${progress(2)}<div class="eyebrow">Practice without pressure</div><h1>Three questions.<br>One clearer picture.</h1><p class="muted">${esc(lesson.title)} · Your answers are graded on the server.</p><div class="content-layout"><form id="quiz-form" class="card">${questions(lesson)}<button class="primary" type="submit">Check my understanding →</button></form><aside class="card side"><h2>It’s okay to miss one.</h2><p class="muted">A mistake tells you where to focus next. Nothing here changes your exam readiness score.</p><button id="reread" class="secondary">Read the lesson again</button></aside></div>`);
 bind('reread',()=>showLesson());
 document.querySelector('#quiz-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{const r=await api('/api/submit',{attempt_id:attemptId,lesson_id:lesson.id,journey_id:journey,answers:answers(lesson)});state.latest=r;await openFeedback(r);}catch(e){error(e);}finally{b.disabled=false;}});
}
async function openFeedback(result){
 await api('/api/feedback',{attempt_id:result.attempt_id});feedback=result;lesson=state.lessons.find(l=>l.id===result.lesson_id);
 const weak=result.results.filter(r=>!r.correct);const recovery=state.variant==='recovery';
 render(`${progress(3)}<div class="eyebrow">Reflect, then take one small step</div><h1>${weak.length?'Your mistakes have a next step.':'You’ve got the key ideas.'}</h1><div class="content-layout"><section class="card"><div class="section-title"><h2>Your understanding</h2><span class="score">${result.score}<span class="muted">/${result.total}</span></span></div>${result.results.map(r=>`<article class="feedback-item"><span class="badge ${r.correct?'correct':'wrong'}">${r.correct?'Understood':'Revisit'} · ${esc(r.concept)}</span><h3>${esc(r.prompt)}</h3><p>Your answer: ${esc(r.options[r.chosen])}</p><p><strong>Correct answer:</strong> ${esc(r.options[r.answer])}</p><p class="muted">${esc(r.explanation)}</p>${recovery&&!r.correct?`<div class="note"><strong>Revisit this idea:</strong> ${esc(lesson.cards[r.card].text)}</div>`:''}</article>`).join('')}</section><aside class="side"><div class="callout"><div class="eyebrow">${recovery?'A focused revision plan':'Keep your practice going'}</div><h2>${recovery?(weak.length?`Revisit ${weak.length} ${weak.length===1?'distinction':'distinctions'}.`:'Reinforce what you know.'):'Return for another practice.'}</h2><p>${recovery?(weak.length?weak.map(r=>esc(r.concept)).join(' · '):'A short return session can reinforce the lesson.'):'Save this lesson for another session tomorrow.'}</p><p class="small">No reminder will be sent. Your plan appears here when you return.</p><button id="save-plan" class="primary full">Save my next session →</button></div><p class="note">${recovery?'Focused feedback':'Standard feedback'} variant. Assigned once per anonymous learner. A/B comparison is a proposal, not proof of uplift.</p><div class="actions"><button id="home" class="secondary">Back to lessons</button></div></aside></div>`);
 bind('save-plan',async()=>{state.plan=await api('/api/plan',{attempt_id:result.attempt_id});home();});bind('home',()=>home());
}
function revision(){
 lesson=state.lessons.find(l=>l.id===state.plan.lesson_id);
 render(`<div class="eyebrow">Close your learning loop</div><h1>A short return.<br>A stronger distinction.</h1><p class="muted">${esc(lesson.title)} · Suggested return ${esc(fmt(state.plan.due_at))}</p><div class="content-layout"><form id="review-form" class="card">${questions(lesson)}<button class="primary" type="submit">Complete revision →</button></form><aside class="card side"><h2>Recall before rereading.</h2><p class="muted">Try the distinctions from memory. This is a repeat quiz, not an independent test of learning gains.</p><button id="home" class="secondary">Back to lessons</button></aside></div>`);
 bind('home',()=>home());document.querySelector('#review-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{const r=await api('/api/review',{answers:answers(lesson)});state=(await api('/api/session'));render(`<div class="eyebrow">Loop closed</div><h1>You showed up again.</h1><section class="card"><h2>Revision score: ${r.score}/${r.total}</h2><p class="muted">${r.already_completed?'This revision had already been saved.':'Your revision is saved.'} Same-day practice does not count as next-day retention.</p><button id="home" class="primary">Choose another lesson →</button></section>`);bind('home',()=>home());}catch(e){error(e);}finally{b.disabled=false;}});
}
function pct(n,d){return d?`${(100*n/d).toFixed(1)}%`:'—';}
async function insights(){
 tabs('insights');const d=await api('/api/analytics?source='+dataset);
 const sum=k=>d.funnel.reduce((n,r)=>n+r[k],0);const stages=[['Lesson started','started'],['Quiz submitted','quiz'],['Feedback opened','feedback'],['Next session saved','saved']];
 const retTotal=d.retention.reduce((n,r)=>n+r.eligible,0),returned=d.retention.reduce((n,r)=>n+r.returned,0);
 render(`<div class="eyebrow">From behavior to better decisions</div><h1>Measure the loop.<br>Question the conclusion.</h1><div class="dataset"><label for="dataset">Dataset</label><select id="dataset"><option value="synthetic" ${dataset==='synthetic'?'selected':''}>Synthetic demonstration</option><option value="local" ${dataset==='local'?'selected':''}>This instance’s activity</option></select><span class="muted small">No learner identifiers displayed</span></div><div class="banner">${esc(d.notice)}</div>
 <div class="metrics"><div class="card metric"><span>STARTED JOURNEYS</span><strong>${sum('started')}</strong><span>Ordered funnel · same journey · 24h</span></div><div class="card metric"><span>PLAN SAVE RATE</span><strong>${pct(sum('saved'),sum('started'))}</strong><span>Saved / started journeys</span></div><div class="card metric"><span>NEXT-DAY RETURN</span><strong>${pct(returned,retTotal)}</strong><span>${returned} / ${retTotal} mature learners · UTC calendar day</span></div></div>
 <div class="grid"><section class="card"><div class="eyebrow">Activation funnel</div><h2>Where does intent disappear?</h2>${d.funnel.length?d.funnel.map(r=>`<h3>${r.variant==='recovery'?'Focused recovery':'Standard feedback'} <span class="muted small">(${r.started} journeys)</span></h3>${stages.map(([label,k])=>`<div class="funnel-row"><div class="row-label"><span>${label}</span><span>${r[k]} · ${pct(r[k],r.started)}</span></div><progress class="funnel-progress ${r.variant==='recovery'?'alt':''}" max="${Math.max(r.started,1)}" value="${r[k]}" aria-label="${esc(label)}: ${r[k]} of ${r.started}"></progress></div>`).join('')}`).join(''):'<p class="empty">Complete a lesson to see this instance’s funnel.</p>'}</section>
 <section class="card"><div class="eyebrow">Retention cohorts</div><h2>Did learners come back?</h2><p class="muted small">${esc(d.retention_definition)}. Return means a lesson start or revision completion.</p><div class="table-wrap"><table><thead><tr><th>Cohort (UTC)</th><th>Variant</th><th>Eligible</th><th>D1</th><th>Rate</th></tr></thead><tbody>${d.retention.length?d.retention.map(r=>`<tr><td>${esc(r.cohort)}</td><td>${esc(r.variant)}</td><td>${r.eligible}</td><td>${r.returned}</td><td>${pct(r.returned,r.eligible)}</td></tr>`).join(''):'<tr><td colspan="5">No mature D1 cohorts yet. Return tomorrow; wait for the full D1 window.</td></tr>'}</tbody></table></div><div class="note"><strong>Decision rule:</strong> prioritize completion of meaningful practice, with D1 as a secondary measure. Guard against faster clicks without comprehension. Synthetic differences are constructed, not statistically tested evidence.</div></section></div>
 <div class="grid section-title"><section class="card"><div class="eyebrow">Experiment proposal</div><h2>One change. One testable idea.</h2><p class="muted">Hypothesis: turning wrong answers into specific revision steps increases plan saves and subsequent practice.</p><p class="small">Control: standard explanation + generic return prompt.<br>Recovery: the same answer + relevant lesson excerpt + named revision targets.</p><p class="note">Random assignment is stable per learner. No sample-size target or experiment outcome is claimed. Define eligibility, duration, minimum detectable effect and stopping rules before recruiting users.</p></section><section class="card"><div class="eyebrow">Instrumentation health</div><h2>Local first. Forward by choice.</h2><p><strong>${d.events}</strong> events in selected dataset.</p><p><strong>${d.outbox_pending}</strong> consented local events awaiting forwarding.</p><p class="muted">PostHog relay ${d.posthog_configured?'configured':'not configured'}. Synthetic events never enter the relay. Delivery is at least once, with stable event UUIDs.</p><p class="note">SQL definitions are versioned in <code>sql/funnel.sql</code> and <code>sql/retention.sql</code>. Refresh to update this snapshot.</p><button id="refresh" class="secondary">Refresh insights</button></section></div>`);
 document.querySelector('#dataset').addEventListener('change',async e=>{dataset=e.target.value;try{await insights();}catch(e){error(e);}});bind('refresh',()=>insights());
}
bind('learn-tab',()=>home());bind('insights-tab',()=>insights());
bind('privacy',()=>{document.querySelector('#consent').checked=!!state.consent;document.querySelector('#privacy-dialog').showModal();});bind('close-privacy',()=>document.querySelector('#privacy-dialog').close());bind('save-consent',async()=>{const r=await api('/api/consent',{enabled:document.querySelector('#consent').checked});state.consent=r.consent;document.querySelector('#privacy-dialog').close();});
(async()=>{try{state=await api('/api/session');home();}catch(e){render('<h1>Unable to open your learning space.</h1><p>Check the server and reload this page.</p>');error(e);}})();
